Project eKomerce {
database_type: 'PostgreSQL'
Note: 'eKomerce'
}

Table account {
  id integer [primary key]
  username varchar(max_length 50)
  email varchar(max_length 127)
  first_name varchar (max_length 150)
  last_name  varchar(max_length 150)
  is_staff BooleanField(default False)
  is_active BooleanField(default True)
  is_superuser BooleanField(default True)
  created_at datetime(default now())
  address_id integer (FK Unique)
}

Table address{
  id integer [primary key]
  street varchar(max_length 127)
  cep varchar(length 8)
  number varchar(max_length 127)
}

Table product{
  id integer [primary key]
  name varchar(max_length 127)
  category varchar (max_length 50)
  price numeric (decimal_fields 2, max_length 8)
  quantity integer(min 0)
  Available BooleanField(default True)
  seller_id integer(Fk)
}

Table cart{
  id integer [primary key]
  account_id integer (FK)
}

Table cart_product{
  id integer [primary key]
  cart_id integer (FK)
  product_id integer (FK)
  quantity integer 
}

table order{
  id integer [primary key]
  account_id integer(FK)
  status status
  cart_id integer(FK)
  created_at datetime (default now())
}

Enum status{
  "Pedido REALIZADO"
  "EM ANDAMENTO"
  "ENTREGUE"
}

REF: address.id - account.address_id // 1:1
REF: account.id < product.seller_id // 1:M
REF: cart.id < cart_product.cart_id //1:M cart_product
REF: product.id < cart_product.product_id //1:M cart_product
REF: order.account_id > account.id // M:1
REF: account.id - cart.account_id // 1:1
REF: cart.id - order.cart_id 
