# Generated by Django 4.2 on 2023-05-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=127)),
                ("cep", models.CharField(max_length=8)),
                ("number", models.CharField(max_length=127)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
