# Generated by Django 4.2 on 2023-05-04 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0002_alter_address_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_address",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
