# Generated by Django 4.2 on 2023-05-04 17:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_alter_address_account"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="account",
        ),
    ]
