# Generated by Django 4.2 on 2023-05-03 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Shirt", "Shirt"),
                            ("T-Shirt", "T Shirt"),
                            ("Jackets", "Jackets"),
                            ("Pants", "Pants"),
                            ("Shorts", "Shorts"),
                            ("Underwear", "Underwear"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
